export const CHANNEL_LIST_REQUEST = "CHANNEL_LIST_REQUEST";
export const CHANNEL_LIST_SUCCESS = "CHANNEL_LIST_SUCCESS";
export const CHANNEL_LIST_FAIL = "CHANNEL_LIST_FAIL";
export const CHANNEL_LIST_RESET = "CHANNEL_LIST_RESET";

export const CHANNEL_CREATE_REQUEST = "CHANNEL_CREATE_REQUEST";
export const CHANNEL_CREATE_SUCCESS = "CHANNEL_CREATE_SUCCESS";
export const CHANNEL_CREATE_FAIL = "CHANNEL_CREATE_FAIL";
export const CHANNEL_CREATE_RESET = "CHANNEL_CREATE_RESET";

export const CHANNEL_DETAIL_REQUEST = "CHANNEL_DETAIL_REQUEST";
export const CHANNEL_DETAIL_SUCCESS = "CHANNEL_DETAIL_SUCCESS";
export const CHANNEL_DETAIL_FAIL = "CHANNEL_DETAIL_FAIL";

export const CHANNEL_UPDATE_MY_REQUEST = "CHANNEL_UPDATE_MY_REQUEST";
export const CHANNEL_UPDATE_MY_SUCCESS = "CHANNEL_UPDATE_MY_SUCCESS";
export const CHANNEL_UPDATE_MY_FAIL = "CHANNEL_UPDATE_MY_FAIL";

export const CHANNEL_DETAIL_MY_REQUEST = "CHANNEL_DETAIL_MY_REQUEST";
export const CHANNEL_DETAIL_MY_SUCCESS = "CHANNEL_DETAIL_MY_SUCCESS";
export const CHANNEL_DETAIL_MY_FAIL = "CHANNEL_DETAIL_MY_FAIL";
export const CHANNEL_DETAIL_MY_RESET = "CHANNEL_DETAIL_MY_RESET";

export const CHANNEL_DELETE_MY_REQUEST = "CHANNEL_DELETE_MY_REQUEST";
export const CHANNEL_DELETE_MY_SUCCESS = "CHANNEL_DELETE_MY_SUCCESS";
export const CHANNEL_DELETE_MY_FAIL = "CHANNEL_DELETE_MY_FAIL";
